one_hot_encoded_columns:
  test_size: 0.2
  random_state: 42
  features:
    - Age
    - Campaign Calls
    - Previous Contact Days
    - Occupation_blue-collar
    - Occupation_entrepreneur
    - Occupation_housemaid
    - Occupation_management
    - Occupation_retired
    - Occupation_self-employed
    - Occupation_services
    - Occupation_student
    - Occupation_technician
    - Occupation_unemployed
    - Occupation_unknown
    - Marital Status_married
    - Marital Status_single
    - Marital Status_unknown
    - Education Level_basic.6y
    - Education Level_basic.9y
    - Education Level_high.school
    - Education Level_illiterate
    - Education Level_professional.course
    - Education Level_university.degree
    - Education Level_unknown
    - Credit Default_unknown
    - Credit Default_yes
    - Housing Loan_unknown
    - Housing Loan_yes
    - Personal Loan_unknown
    - Personal Loan_yes
    - Contact Method_telephone

label_encoded_dataset_columns:
  test_size: 0.2
  random_state: 3
  features:
    - Age
    - Occupation
    - Marital Status
    - Education Level
    - Credit Default
    - Housing Loan
    - Personal Loan
    - Contact Method
    - Campaign Calls
    - Previous Contact Days

random_forest_model_parameters:
  n_estimators: 545 
  random_state: 42
  max_depth: 5
  n_jobs: -1
  class_weight: 'balanced'
  max_features: 'log2'
  min_samples_split: 9
  min_samples_leaf: 1

number_cols:
  features:
    - Age
    - Campaign Calls
    - Previous Contact Days

xgboost_model_parameters:
  n_estimators: 427
  learning_rate: 0.01
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.6
  scale_pos_weight: 8
  random_state: 42
  gamma: 0.3
  reg_lambda: 1
  reg_alpha: 0.01

catboost_model_parameters:
  random_strength: 20
  learning_rate: 0.01
  l2_leaf_reg: 8
  iterations: 1000
  depth: 4
  border_count: 160
  bagging_temperature: 0.4444444444444444
  random_seed: 42
  class_weights: [1, 8]
